### ISSUE TITLE
Get Books Angular Service

### ISSUE THREAD

**Issue by jmoore53** [jmoore53/fisher-bookstore#17]
## Angular Error
Compiles Successfully, but it won't make GET requests to the API to https://localhost:5001/api/books using the angular [book-service](https://github.com/jmoore53/fisher-bookstore/blob/Lab7/web/src/app/books/books.service.ts). It looks like it runs into data structure error or the request is being called from the wrong spot. (Directions in Lab7 didn't give a location to call from or specific data structure to use)

See [`./web/src/app/books/books/books.component.ts` - Line 26, and the File](https://github.com/jmoore53/fisher-bookstore/blob/Lab7/web/src/app/books/books/books.component.ts#L26) for the book-service injection and GET call into variable. Can you take a look at this?

## Results in the Browser from Current Component
![image](https://user-images.githubusercontent.com/10286014/55776711-a05d9980-5a6b-11e9-8ee6-5e553196fbb2.png)

**Comment by skyarkitekten** [comment]
Verify that you Book model in the API is the same as the Book model in your Angular app form Lab 6.

**Comment by jmoore53** [comment]
In the `books.components.ts` file, I added 
```ts
  books: Book[];

  constructor(private bookService: BooksService){}

  fetchBooks(){
    this.bookService.getBooks().subscribe(books => (this.books = books));
    console.log(this.books)
  }


  ngOnInit() {
    this.fetchBooks();
  }
```
This `subscribe` method allowed me to make a request to the dotnet api.. With this I was able to make requests, but there was a dotnet error in the browser saying something about `https` on `5001` port. I fixed this commenting out the use https redirection in the api `startup.cs` file. 

```cs
app.UseCors("CorsPolicy");
//app.UseHttpsRedirection();
app.UseMvc();
```

**Comment by skyarkitekten** [comment]
have a look at my code running end to end:
https://github.com/amis-3610/fisher-bookstore
